AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Flash card word game backend (Cognito + DynamoDB + Lambda)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        WORDS_TABLE: !Ref WordsTable

Parameters:
  StageName:
    Type: String
    Default: v1
  AllowedOrigin:
    Type: String
    Default: "*"

Resources:
  WordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: wordId
          AttributeType: S
      KeySchema:
        - AttributeName: wordId
          KeyType: HASH

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: flash-card-word-game-users
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: flash-card-word-game-web
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  FrontendOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub ${AWS::StackName}-frontend-oai

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontReadAccess
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt FrontendOriginAccessIdentity.S3CanonicalUserId
            Action:
              - s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub ${AWS::StackName} frontend distribution
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        Origins:
          - Id: FrontendS3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${FrontendOriginAccessIdentity}
        DefaultCacheBehavior:
          TargetOriginId: FrontendS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      CorsConfiguration:
        AllowOrigins:
          - !Ref AllowedOrigin
        AllowHeaders:
          - Authorization
          - Content-Type
        AllowMethods:
          - GET
          - POST
          - OPTIONS
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            JwtConfiguration:
              issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}
              audience:
                - !Ref UserPoolClient
            IdentitySource: "$request.header.Authorization"

  PutWordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/functions/
      Handler: put_word.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WordsTable
      Events:
        PutWord:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /words

  BulkPutWordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/functions/
      Handler: bulk_put_words.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WordsTable
      Events:
        BulkPutWords:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: POST
            Path: /words/bulk

  GetRandomWordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/functions/
      Handler: get_random_words.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref WordsTable
      Events:
        RandomWords:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /words/random

Outputs:
  ApiBaseUrl:
    Description: Base URL for the authenticated API
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  CognitoUserPoolClientId:
    Description: Cognito app client ID for web auth
    Value: !Ref UserPoolClient
  AwsRegion:
    Description: AWS region where resources were created
    Value: !Ref AWS::Region
  WordsTableName:
    Description: DynamoDB table storing Spanish/Bulgarian words
    Value: !Ref WordsTable
  FrontendBucketName:
    Description: S3 bucket for static frontend hosting
    Value: !Ref FrontendBucket
  FrontendDistributionId:
    Description: CloudFront distribution ID for frontend
    Value: !Ref FrontendDistribution
  FrontendDistributionDomainName:
    Description: CloudFront domain name for frontend
    Value: !GetAtt FrontendDistribution.DomainName
  FrontendAppUrl:
    Description: HTTPS URL for the hosted frontend
    Value: !Sub https://${FrontendDistribution.DomainName}
